const store = "course"

export const GO_TO_STEP = `${store}/GO_TO_STEP`
export const FETCH_INSTRUCTOR_COURSE_DETAIL = `${store}/FETCH_INSTRUCTOR_COURSE_DETAIL`
export const UPDATE_INSTRUCTOR_COURSE = `${store}/UPDATE_INSTRUCTOR_COURSE`

export default class ManageCourseAction {
  static FETCH_INSTRUCTOR_COURSE_DETAIL = {
    REQUEST: `${store}/FETCH_INSTRUCTOR_COURSE_DETAIL_REQUEST`,
    SUCCESS: `${store}/FETCH_INSTRUCTOR_COURSE_DETAIL_SUCCESS`,
    ERROR: `${store}/FETCH_INSTRUCTOR_COURSE_DETAIL_ERROR`
  }

  static UPDATE_INSTRUCTOR_COURSE = {
    REQUEST: `${store}/UPDATE_INSTRUCTOR_COURSE_REQUEST`,
    SUCCESS: `${store}/UPDATE_INSTRUCTOR_COURSE_SUCCESS`,
    ERROR: `${store}/UPDATE_INSTRUCTOR_COURSE_ERROR`
  }
}
