const store = "course"

export const GO_TO_STEP = `${store}/GO_TO_STEP`
export const FETCH_INSTRUCTOR_COURSE_DETAIL = `${store}/FETCH_INSTRUCTOR_COURSE_DETAIL`
export const UPDATE_INSTRUCTOR_COURSE = `${store}/UPDATE_INSTRUCTOR_COURSE`
export const FETCH_COURSE_LECTURE = `${store}/FETCH_COURSE_LECTURE`
export const DELETE_COURSE_LECTURE = `${store}/DELETE_COURSE_LECTURE`
export const UPDATE_COURSE_LECTURE = `${store}/UPDATE_COURSE_LECTURE`
export const UPDATE_LECTURE_SECTION = `${store}/UPDATE_LECTURE_SECTION`

export default class ManageCourseAction {
  static FETCH_INSTRUCTOR_COURSE_DETAIL = {
    REQUEST: `${store}/FETCH_INSTRUCTOR_COURSE_DETAIL_REQUEST`,
    SUCCESS: `${store}/FETCH_INSTRUCTOR_COURSE_DETAIL_SUCCESS`,
    ERROR: `${store}/FETCH_INSTRUCTOR_COURSE_DETAIL_ERROR`
  }

  static UPDATE_INSTRUCTOR_COURSE = {
    REQUEST: `${store}/UPDATE_INSTRUCTOR_COURSE_REQUEST`,
    SUCCESS: `${store}/UPDATE_INSTRUCTOR_COURSE_SUCCESS`,
    ERROR: `${store}/UPDATE_INSTRUCTOR_COURSE_ERROR`
  }

  static FETCH_COURSE_LECTURE = {
    REQUEST: `${store}/FETCH_COURSE_LECTURE_REQUEST`,
    SUCCESS: `${store}/FETCH_COURSE_LECTURE_SUCCESS`,
    ERROR: `${store}/FETCH_COURSE_LECTURE_ERROR`
  }

  static DELETE_COURSE_LECTURE = {
    REQUEST: `${store}/DELETE_COURSE_LECTURE_REQUEST`,
    SUCCESS: `${store}/DELETE_COURSE_LECTURE_SUCCESS`,
    ERROR: `${store}/DELETE_COURSE_LECTURE_ERROR`
  }

  static UPDATE_COURSE_LECTURE = {
    REQUEST: `${store}/UPDATE_COURSE_LECTURE_REQUEST`,
    SUCCESS: `${store}/UPDATE_COURSE_LECTURE_SUCCESS`,
    ERROR: `${store}/UPDATE_COURSE_LECTURE_ERROR`
  }

  static UPDATE_LECTURE_SECTION = {
    REQUEST: `${store}/UPDATE_LECTURE_SECTION_REQUEST`,
    SUCCESS: `${store}/UPDATE_LECTURE_SECTION_SUCCESS`,
    ERROR: `${store}/UPDATE_LECTURE_SECTION_ERROR`
  }
}
